# Generated by Django 2.2.3 on 2020-06-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200613_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='phonenumber',
        ),
    ]
